language: python
python:
  - "2.7"
  - "3.5"
  # PyPy versions
  - "pypy2.7"
  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - virtualenv venv
  - source venv/bin/activate
  - pip install flask flask-jsonpify flask-sqlalchemy flask-restful
  - pip freeze
  # - pip install pytest
# command to run tests
script:
  - python server.py runserver
#  - pytest # or py.test for Python versions 3.5 and below