
FROM python:3.3

ADD server.py /
RUN pip -V
COPY . /opt/app
WORKDIR /opt/app
RUN pip install -r requirements.txt

COPY requirements.txt /opt/app/requirements.txt
WORKDIR /opt/app
RUN pip install -r requirements.txt
COPY . /opt/app

CMD [ "python", "./server.py" ]
