
FROM python:2.7

ADD server.py /
RUN pip -V
COPY . /opt/app
WORKDIR /opt/app
RUN pip install -r requirements.txt

COPY requirements.txt /opt/app/requirements.txt
WORKDIR /opt/app
RUN pip install -r requirements.txt
RUN pip install pytest
RUN pytest
COPY . /opt/app

CMD [ "python", "./server.py" ]
